name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 */3 * * *' # Runs every 3 hours, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in michimani.net posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://michimani.net/index.xml"